/*
 * GripPipeline.h
 *
 *  Created on: Jan 9, 2018
 *      Author: RatPack
 */

#ifndef SRC_GRIPPIPELINE_H_
#define SRC_GRIPPIPELINE_H_

#pragma once
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>
#include <WPILib.h>

namespace grip {

/**
* GripPipeline class.
*
* An OpenCV pipeline generated by GRIP.
*/
class GripPipeline {
	private:
		cv::Mat hslThresholdOutput;
		void hslThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);

	public:
		GripPipeline();
		void Process(cv::Mat& source0);
		cv::Mat* GetHslThresholdOutput();
};


} // end namespace grip




#endif /* SRC_GRIPPIPELINE_H_ */
